[Expenses:Database]
DbHost=${EXPENSES_DATABASE_DB_HOST}
DbPort=${EXPENSES_DATABASE_DB_PORT}
DbUser=${EXPENSES_DATABASE_DB_USER}
DbPassword=${EXPENSES_DATABASE_DB_PASSWORD}
DbName=${EXPENSES_DATABASE_DB_NAME}

[Expenses:Cors]
AllowedOrigins=${EXPENSES_CORS_ALLOWED_ORIGINS}
