[Db]
Host=${EXPENSES_BACKEND_DB_HOST}
Port=${EXPENSES_BACKEND_DB_PORT}
User=${EXPENSES_BACKEND_DB_USER}
Password=${EXPENSES_BACKEND_DB_PASSWORD}
Name=${EXPENSES_BACKEND_DB_NAME}

[Cors]
AllowedOrigins=${EXPENSES_BACKEND_CORS_ALLOWED_ORIGINS}
